ALTER TABLE users
  ADD COLUMN IF NOT EXISTS full_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS phone VARCHAR(50),
  ADD COLUMN IF NOT EXISTS work_authorization VARCHAR(100),
  ADD COLUMN IF NOT EXISTS years_experience INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS salary_expectation_min INTEGER,
  ADD COLUMN IF NOT EXISTS salary_expectation_max INTEGER,
  ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR(255),
  ADD COLUMN IF NOT EXISTS portfolio_url VARCHAR(255),
  ADD COLUMN IF NOT EXISTS bio_summary TEXT,
  ADD COLUMN IF NOT EXISTS job_titles TEXT[] DEFAULT '{}';